site_name: PrairieChansons
nav:
  - Home: index.md
  - 1: 1.md
theme:
  name: material
plugins:
  - search
  - mermaid2:
      version: 10.0.2
  - blog
  - group:
      collapse: true
  - offline
  - social
  - tags